# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CallkitSample-iOS13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Stringee'
  pod 'SwiftyJSON', '~> 4.0'

end
