platform :ios, '9.0'

target 'ChatSampleSwift' do
  use_frameworks!
  
  pod 'SnapKit', '~> 4.2'
  pod 'pop', '~> 1.0'
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
  pod 'MBProgressHUD', '~> 1.1'
  pod 'AXPhotoViewer/SDWebImage'
  pod 'AXPhotoViewer/Core'
  pod 'Parchment'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SSZipArchive'
  pod 'KafkaRefresh'

end
