platform :ios, '13.0'

target 'ChatSampleSwift' do
  use_frameworks!
  
  pod 'SnapKit', '~> 4.2'
  pod 'pop', '~> 1.0'
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
  pod 'MBProgressHUD', '~> 1.1'
  pod 'AXPhotoViewer/SDWebImage'
  pod 'AXPhotoViewer/Core'
  pod 'Parchment'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SSZipArchive'
  pod 'KafkaRefresh'
  pod 'Stringee'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
